name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install package
      run: pip install -e .
    - name: Install dependencies
      run: pip install -r dev-requirements.txt
    - name: Check if blacken-docs needs to be run
      run: blacken-docs README.md
    - name: Run tests
      run: ./runtests
