name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        python: ["3.6", "3.7", "3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install package
      run: pip install -e .
    - name: Install dependencies
      run: pip install -r dev-requirements.txt
    - name: Check if blacken-docs needs to be run
      run: blacken-docs -l 60 docs/*.rst
    - name: Run tests
      run: ./runtests
